name = "Code GBT (alpha)"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-01"
open_weights = true
status = "alpha"

[cost]
input = 1.0
output = 3.0

[limit]
context = 200000
output = 128000

[modalities]
input = ["text"]
output = ["text"]