name = "MiniMax M2 (alpha)"
release_date = "2025-10-27"
last_updated = "2025-10-27"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2024-10"
open_weights = true
status = "alpha"

[cost]
input = 1.2
output = 1.2

[limit]
context = 200_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
