name = "Qwen3 Coder"
release_date = "2025-07-23"
last_updated = "2025-07-23"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.45
output = 1.8

[limit]
context = 262_144
output = 65_536

[modalities]
input = ["text"]
output = ["text"]