name = "Qwen2.5-Coder-32B-Instruct"
release_date = "2024-11-11"
last_updated = "2024-11-11"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-10"
tool_call = false
open_weights = true

[cost]
input = 0.8
output = 0.8

[limit]
context = 32768
output = 32768

[modalities]
input = ["text"]
output = ["text"]
