name = "Kimi K2 Instruct 0905"
release_date = "2024-09-05"
last_updated = "2024-09-05"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.296176
output = 1.18528

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]