name = "GPT OSS 120B"
release_date = "2024-01-01"
last_updated = "2025-10-04"
attachment = true
reasoning = true
temperature = true
knowledge = "2024-01"
tool_call = true
open_weights = false

[cost]
input = 0.15
output = 0.60

[limit]
context = 131072
output = 8192

[modalities]
input = ["text"]
output = ["text"]
