name = "Grok 4"
release_date = "2025-07-09"
last_updated = "2025-07-09"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-01-01"
tool_call = true
open_weights = false

[cost]
input = 3.00
output = 15.00
cache_read = 0.75


[limit]
context = 256_000
output = 256_000

[modalities]
input = ["image", "text"]
output = ["text"]
