name = "Grok Code Fast 1"
release_date = "2025-08-26"
last_updated = "2025-08-26"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-08"
tool_call = true
open_weights = false

[cost]
input = 0.20
output = 1.50
cache_read = 0.02

[limit]
context = 256_000
output = 10_000

[modalities]
input = ["text"]
output = ["text"]
