id = "hf:moonshotai/Kimi-K2-Instruct"
name = "Kimi K2"
release_date = "2025-07-11"
last_updated = "2025-07-11"
attachment = false
reasoning = false
temperature = true
tool_call = true
knowledge = "2024-10"
open_weights = true

[cost]
input = 0.60
output = 2.50

[limit]
context = 128_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
