name = "DeepSeek R1 Distill Qwen 32B"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.287
output = 0.861

[limit]
context = 32_768
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
