name = "DeepSeek V3.2 Exp"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.287
output = 0.431

[limit]
context = 131_072
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
