name = "QVQ Max"
release_date = "2025-03-25"
last_updated = "2025-03-25"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 1.147
output = 4.588

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
