name = "Qwen2.5 72B Instruct"
release_date = "2024-09"
last_updated = "2024-09"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = true

[cost]
input = 0.574
output = 1.721

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
