name = "Qwen Flash"
release_date = "2025-07-28"
last_updated = "2025-07-28"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.022
output = 0.216

[limit]
context = 1_000_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
