name = "Qwen3-Next 80B-A3B Instruct"
release_date = "2025-09"
last_updated = "2025-09"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.144
output = 0.574

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
