name = "Qwen-Omni Turbo"
release_date = "2025-01-19"
last_updated = "2025-03-26"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.058
output = 0.23
input_audio = 3.584
output_audio = 7.168

[limit]
context = 32_768
output = 2_048

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text", "audio"]
