name = "Qwen-MT Plus"
release_date = "2025-01"
last_updated = "2025-01"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = false
open_weights = false

[cost]
input = 0.259
output = 0.775

[limit]
context = 16_384
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
