name = "Qwen-VL OCR"
release_date = "2024-10-28"
last_updated = "2025-04-13"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = false
open_weights = false

[cost]
input = 0.717
output = 0.717

[limit]
context = 34_096
output = 4_096

[modalities]
input = ["text", "image"]
output = ["text"]
