name = "Qwen Turbo"
release_date = "2024-11-01"
last_updated = "2025-07-15"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.044
output = 0.087
reasoning = 0.431

[limit]
context = 1_000_000
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
