name = "QwQ 32B"
release_date = "2024-12"
last_updated = "2024-12"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = true

[cost]
input = 0.287
output = 0.861

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
