name = "Tongyi Intent Detect V3"
release_date = "2024-01"
last_updated = "2024-01"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = false
open_weights = false

[cost]
input = 0.058
output = 0.144

[limit]
context = 8_192
output = 1_024

[modalities]
input = ["text"]
output = ["text"]
