name = "DeepSeek V3.1"
release_date = "2025-08-20"
last_updated = "2025-08-26"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-07"
tool_call = true
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]