name = "DeepSeek R1"
release_date = "2024-11-01"
last_updated = "2025-09-05"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-11"
tool_call = false
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]