name = "Qwen3 30B A3B Thinking 2507"
release_date = "2025-07-29"
last_updated = "2025-07-29"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.20
output = 0.80

[limit]
context = 262_000
output = 262_000

[modalities]
input = ["text"]
output = ["text"]
