name = "Qwen3 Coder (exacto)"
release_date = "2025-07-23"
last_updated = "2025-07-23"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.38
output = 1.53

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
