name = "Qwen3 Max"
release_date = "2025-09-05"
last_updated = "2025-09-05"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
# cost at >= 128k context
# input = 1
# output = 5
input = 1.20
output = 6.00

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
