name = "DeepSeek V3 0324"
release_date = "2025-03-24"
last_updated = "2025-03-24"
knowledge = "2024-07"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true


[cost]
input = 0.447
output = 1.342

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]