name = "Gemini 2.5 Pro"
release_date = "2025-03-20"
last_updated = "2025-06-17"
knowledge = "2025-01"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = false


[cost]
input = 1.3416
output = 8.944

[limit]
context = 1_048_576
output = 65_535

[modalities]
input = ["text", "image"]
output = ["text"]