name = "GPT Oss 120b"
release_date = "2025-08-05"
last_updated = "2025-08-05"
knowledge = "2024-01"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true


[cost]
input = 0
output = 0

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]