name = "Kimi K2 Instruct"
release_date = "2025-07-11"
last_updated = "2025-09-05"
knowledge = "2024-07"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true


[cost]
input = 0.551
output = 2.646

[limit]
context = 131_000
output = 131_000

[modalities]
input = ["text"]
output = ["text"]