name = "Nova Pro 1.0"
release_date = "2024-12-03"
last_updated = "2024-12-03"
knowledge = "2024-04"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = false


[cost]
input = 1.016
output = 4.061

[limit]
context = 300_000
output = 5_000

[modalities]
input = ["text", "image"]
output = ["text"]