name = "GLM 4.5 Air"
release_date = "2025-07-28"
last_updated = "2025-07-28"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.10
output = 0.50

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]