name = "Qwen3 VL Instruct"
release_date = "2025-09-24"
last_updated = "2025-09-24"
attachment = true
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.7
output = 2.8

[limit]
context = 131_072
output = 129_024

[modalities]
input = ["text", "image"]
output = ["text"]
