name = "Qwen3 Max"
release_date = "2025-09-23"
last_updated = "2025-09-23"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = false

[cost]
input = 1.2
output = 6.0
cached_input = 0.24

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
