name = "Qwen Plus"
release_date = "2024-01-25"
last_updated = "2025-09-11"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.4
output = 1.2
reasoning = 4

[limit]
context = 1_000_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
