name = "Qwen3 14B"
release_date = "2025-04"
last_updated = "2025-04"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.35
output = 1.4
reasoning = 4.2

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
