name = "Qwen3-VL 30B-A3B"
release_date = "2025-04"
last_updated = "2025-04"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.2
output = 0.8
reasoning = 2.4

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
