name = "Qwen3-VL Plus"
release_date = "2025-09-23"
last_updated = "2025-09-23"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = false

[cost]
input = 0.2
output = 1.6
reasoning = 4.8

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
