name = "Qwen3-Omni Flash"
release_date = "2025-09-15"
last_updated = "2025-09-15"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.43
output = 1.66
input_audio = 3.81
output_audio = 15.11

[limit]
context = 65_536
output = 16_384

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text", "audio"]
