name = "Qwen-Omni Turbo Realtime"
release_date = "2025-05-08"
last_updated = "2025-05-08"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.27
output = 1.07
input_audio = 4.44
output_audio = 8.89

[limit]
context = 32_768
output = 2_048

[modalities]
input = ["text", "image", "audio"]
output = ["text", "audio"]
