name = "DeepSeek V3 0324"
release_date = "2025-08-23"
last_updated = "2025-08-23"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.20
output = 0.80

[limit]
context = 75_000
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
