name = "Sonoma Dusk Alpha"
release_date = "2024-09-05"
last_updated = "2024-09-05"
attachment = true
reasoning = false
temperature = false
tool_call = true
open_weights = false

[cost]
input = 0.00
output = 0.00

[limit]
context = 2_000_000
output = 2_000_000

[modalities]
input = ["text", "image"]
output = ["text"]
