id = "hf:deepseek-ai/DeepSeek-R1"
name = "DeepSeek R1"
release_date = "2025-01-20"
last_updated = "2025-01-20"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-01"
tool_call = true
open_weights = true

[cost]
input = 0.55
output = 2.19

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
