id = "hf:deepseek-ai/DeepSeek-R1-0528"
name = "DeepSeek R1 (0528)"
release_date = "2025-08-01"
last_updated = "2025-08-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 3
output = 8

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
