name = "Claude Haiku 4.5"
release_date = "2025-10-15"
last_updated = "2025-10-15"
attachment = true
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-02-31"
open_weights = false

[cost]
input = 1.00
output = 5.00
cache_read = 0.10
cache_write = 1.25

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text", "image"]
output = ["text"]
