name = "DeepSeek V3"
release_date = "2024-05-07"
last_updated = "2025-10-04"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.50
output = 1.50

[limit]
context = 131072
output = 8192

[modalities]
input = ["text"]
output = ["text"]
