name = "DeepSeek R1 Distill Qwen 32B"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = true
knowledge = "2024-10"
release_date = "2025-01-20"
last_updated = "2025-01-20"

[cost]
input = 0.20
output = 0.20

[limit]
context = 121_808
output = 8_192

[modalities]
input = ["text"]
output = ["text"]