name = "Kimi K2 Instruct"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
knowledge = "2024-10"
release_date = "2024-07-18"
last_updated = "2024-07-18"

[cost]
input = 0.20
output = 0.20

[limit]
context = 58_904
output = 4_096

[modalities]
input = ["text"]
output = ["text"]