name = "DeepSeek-V3.2-Exp"
release_date = "2025-09-29"
last_updated = "2025-09-29"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.27
output = 0.41

[limit]
context = 163_000
output = 163_000

[modalities]
input = ["text"]
output = ["text"]
