name = "Gemini 2.5 Pro"
release_date = "2025-09-15"
last_updated = "2025-09-15"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = false

[cost]
input = 1.25
output = 5.00
cache_read = 0.31

[limit]
context = 2_000_000
output = 65_000

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text"]
