name = "Gemini 2.5 Flash"
release_date = "2025-09-15"
last_updated = "2025-09-15"
attachment = true
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = false

[cost]
input = 0.075
output = 0.30
cache_read = 0.02

[limit]
context = 1_000_000
output = 65_000

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text"]
