name = "GLM-4.6"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-04"
open_weights = true

[cost]
input = 0.27
output = 1.10
cache_read = 0.11
cache_write = 0

[limit]
context = 204_800
output = 204_800

[modalities]
input = ["text"]
output = ["text"]
