name = "Qwen3 Coder 480B A35B Instruct"
release_date = "2025-08-01"
last_updated = "2025-08-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.82
output = 3.29

[limit]
context = 262_144
output = 131_000

[modalities]
input = ["text"]
output = ["text"]
