name = "Kimi K2 Instruct 0905"
release_date = "2025-09-05"
last_updated = "2025-09-05"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-08"
tool_call = true
open_weights = true

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]

[cost]
input = 0.60
output = 2.50
