name = "DeepSeek V3.1 Terminus"
release_date = "2025-09-22"
last_updated = "2025-09-25"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 1.20
output = 1.20

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
