name = "GLM 4.5 Air"
release_date = "2025-07-25"
last_updated = "2025-07-25"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-04"
open_weights = true

[cost]
input = 0.11
output = 0.56
cache_read = 0.022

[limit]
context = 128_000
output = 96_000

[modalities]
input = ["text"]
output = ["text"]
