name = "Kimi K2 0905"
release_date = "2025-09-05"
last_updated = "2025-09-05"
attachment = false
reasoning = false
temperature = true
tool_call = true
knowledge = "2024-10"
open_weights = true

[cost]
input = 1.20
output = 1.20

[limit]
context = 128_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
