name = "Claude Sonnet 4.5 (Preview)"
release_date = "2025-09-29"
last_updated = "2025-09-29"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-03-31"
tool_call = true
open_weights = false

[limit]
context = 80_000
output = 16_000

[modalities]
input = ["text", "image"]
output = ["text"]
