name = "Mistral Medium 3"
release_date = "2025-05-07"
last_updated = "2025-05-07"
attachment = true
reasoning = false
temperature = true
knowledge = "2025-05"
tool_call = true
open_weights = false

[cost]
input = 0.40
output = 2.00

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text", "image"]
output = ["text"]
