name = "GLM 4.6"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.6
output = 2.2
cached_input = 0.11

[limit]
context = 200_000
output = 96_000

[modalities]
input = ["text"]
output = ["text"]
