name = "GLM 4.5"
release_date = "2025-07-28"
last_updated = "2025-07-28"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-07"
tool_call = true
open_weights = true

[cost]
input = 0.6
output = 2.2

[limit]
context = 128_000
output = 96_000

[modalities]
input = ["text"]
output = ["text"]
