name = "GPT-OSS-120B"
release_date = "2025-08-04"
last_updated = "2025-08-14"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-08"
tool_call = false
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]