name = "GPT-4o (2024-08-06)"
release_date = "2024-08-06"
last_updated = "2024-08-06"
attachment = true
reasoning = false
temperature = true
knowledge = "2023-09"
tool_call = true
open_weights = false

[cost]
input = 2.50
output = 10.00
cache_read = 1.25

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
