name = "Parakeet TDT 0.6B v2"
release_date = "2024-01-01"
last_updated = "2025-09-05"
attachment = false
reasoning = false
temperature = false
knowledge = "2024-01"
tool_call = false
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 0
output = 4096

[modalities]
input = ["audio"]
output = ["text"]