name = "Qwen3 Next 80B A3B Instruct"
release_date = "2025-09-11"
last_updated = "2025-09-11"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.10
output = 0.80

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
