name = "Sonar Reasoning Pro"
release_date = "2025-02-19"
last_updated = "2025-02-19"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-09"
tool_call = false
open_weights = false

[cost]
input = 2.0
output = 8.0

[limit]
context = 127_000
output = 8_000

[modalities]
input = ["text"]
output = ["text"]
