name = "MiniMax-01"
attachment = true
reasoning = true         
tool_call = true
temperature = true
release_date = "2025-01-15"
last_updated = "2025-01-15"
open_weights = true

[cost]
input = 0.20
output = 1.10

[limit]
context = 1_000_000
output = 1_000_000

[modalities]
input = ["text", "image"]
output = ["text"]