name = "Qwen3 32B (dense)"
release_date = "2025-09-18"
last_updated = "2025-09-18"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = true

[cost]
input = 0.15
output = 0.6

[limit]
context = 16_384
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
