name = "Qwen3 Coder 30B A3B Instruct"
release_date = "2025-09-18"
last_updated = "2025-09-18"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[cost]
input = 0.15
output = 0.6

[limit]
context = 262_144
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
