id = "hf:meta-llama/Llama-3.2-3B-Instruct"
name = "Llama-3.2-3B-Instruct"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-09-18"
last_updated = "2024-10-24"

[cost]
input = 0.06
output = 0.06

[limit]
context = 128000
output = 128000

[modalities]
input = ["text"]
output = ["text"]
