name = "Qwen 3 235B Instruct"
release_date = "2025-07-22"
last_updated = "2025-07-22"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.6
output = 1.2

[limit]
context = 131_000
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
