name = "Z.AI GLM-4.6"
release_date = "2025-11-05"
last_updated = "2025-11-05"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0
output = 0
cache_read = 0
cache_write = 0

[limit]
context = 131_072
output = 40_960

[modalities]
input = ["text"]
output = ["text"]

