name = "Llama-3.1-8B-Instruct"
release_date = "2024-07-23"
last_updated = "2024-07-23"
attachment = false
reasoning = true
temperature = true
knowledge = "2023-12"
tool_call = true
open_weights = true

[cost]
input = 0.20
output = 0.20

[limit]
context = 128_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
