name = "GLM 4.6"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-04"
open_weights = true

[cost]
input = 0.55
output = 2.19

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
