name = "Qwen3 Coder Plus"
release_date = "2025-07-23"
last_updated = "2025-07-23"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 1
output = 5
cache_read = 0.1
cache_write = 1.25

[limit]
context = 1_000_000
output = 66_540

[modalities]
input = ["text"]
output = ["text"]