name = "DeepSeek R1 Distill Llama 70B"
release_date = "2025-01-20"
last_updated = "2025-01-20"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-07"
tool_call = true
open_weights = true

[cost]
input = 0.90
output = 0.90

[limit]
context = 32_000
output = 4096

[modalities]
input = ["text"]
output = ["text"]