name = "Gemma-3-27B-IT"
release_date = "2024-12-01"
last_updated = "2025-09-05"
attachment = true
reasoning = true
temperature = true
knowledge = "2024-12"
tool_call = true
open_weights = false

[cost]
input = 0.25
output = 0.50

[limit]
context = 40_000
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]