name = "Llama-3.3-70B-Instruct"
release_date = "2024-12-06"
last_updated = "2024-12-06"
attachment = true
reasoning = false
temperature = true
knowledge = "2023-12"
tool_call = true
open_weights = true

[cost]
input = 0.90
output = 0.90

[limit]
context = 100_000
output = 4096

[modalities]
input = ["text"]
output = ["text"]