name = "Llama 3.1 8B Instruct"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = false
reasoning = false
temperature = true
knowledge = "2023-12"
tool_call = true
open_weights = true

[cost]
input = 0.20
output = 0.20

[limit]
context = 128_000
output = 16384

[modalities]
input = ["text"]
output = ["text"]