name = "Mistral Small 3.2 24B Instruct (2506)"
release_date = "2025-06-20"
last_updated = "2025-06-20"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.15
output = 0.35

[limit]
context = 128_000
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]