name = "Pixtral 12B 2409"
release_date = "2024-09-25"
last_updated = "2024-09-25"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.20
output = 0.20

[limit]
context = 128_000
output = 4096

[modalities]
input = ["text", "image"]
output = ["text"]