name = "Qwen3 235B A22B Instruct 2507"
release_date = "2025-07-01"
last_updated = "2025-07-01"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.75
output = 2.25

[limit]
context = 260_000
output = 8192

[modalities]
input = ["text"]
output = ["text"]