name = "Qwen3-Coder 30B-A3B Instruct"
release_date = "2025-04"
last_updated = "2025-04"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.20
output = 0.80

[limit]
context = 128_000
output = 8192

[modalities]
input = ["text"]
output = ["text"]