name = "Whisper Large v3"
release_date = "2023-09-01"
last_updated = "2025-09-05"
attachment = false
reasoning = false
temperature = false
knowledge = "2023-09"
tool_call = false
open_weights = true

[cost]
input = 0.003
output = 0.0

[limit]
context = 0
output = 4096

[modalities]
input = ["audio"]
output = ["text"]