name = "KAT-Coder-Pro-V1"
release_date = "2025-10-23"
last_updated = "2025-10-23"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-01-01"
tool_call = true
open_weights = false

[cost]
input = 0.60
output = 2.40
cache_read = 0.12

[limit]
context = 256_000
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
