name = "Qwen3 235B A22B Instruct 2507"
release_date = "2025-08-23"
last_updated = "2025-08-23"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.20
output = 0.30

[limit]
context = 262_144
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
