# https://developers.cloudflare.com/workers-ai/models/aura-1/

name = "@cf/deepgram/aura-1"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2025-08-27"
last_updated = "2025-07-07"

[cost]
# per 1k characters
input = 0.015
output = 0.015

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["audio"]
