# https://developers.cloudflare.com/workers-ai/models/bart-large-cnn/

name = "@cf/facebook/bart-large-cnn"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2022-03-02"
last_updated = "2024-02-13"

[cost]
input = 0
output = 0

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
