# https://developers.cloudflare.com/workers-ai/models/deepseek-coder-6.7b-instruct-awq/

name = "@hf/thebloke/deepseek-coder-6.7b-instruct-awq"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-11-05"
last_updated = "2023-11-13"

[cost]
input = 0
output = 0

[limit]
context = 4096
output = 4096

[modalities]
input = ["text"]
output = ["text"]
