# https://developers.cloudflare.com/workers-ai/models/gemma-7b-it-lora/

name = "@cf/google/gemma-7b-it-lora"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-04-02"
last_updated = "2024-04-02"

[cost]
input = 0
output = 0

[limit]
context = 3500
output = 3500

[modalities]
input = ["text"]
output = ["text"]
