# https://developers.cloudflare.com/workers-ai/models/gpt-oss-120b/

name = "@cf/openai/gpt-oss-120b"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2025-08-04"
last_updated = "2025-08-14"

[cost]
input = 0.35
output = 0.75

[limit]
context = 128000
output = 128000

[modalities]
input = ["text"]
output = ["text"]
