# https://developers.cloudflare.com/workers-ai/models/llama-3-8b-instruct-awq/

name = "@cf/meta/llama-3-8b-instruct-awq"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-05-09"
last_updated = "2024-05-09"

[cost]
input = 0.12
output = 0.27

[limit]
context = 8192
output = 8192

[modalities]
input = ["text"]
output = ["text"]
