# https://developers.cloudflare.com/workers-ai/models/llama-2-7b-chat-hf-lora/

name = "@cf/meta-llama/llama-2-7b-chat-hf-lora"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-07-13"
last_updated = "2024-04-17"

[cost]
input = 0
output = 0

[limit]
context = 8192
output = 8192

[modalities]
input = ["text"]
output = ["text"]
