# https://developers.cloudflare.com/workers-ai/models/melotts/

name = "@cf/myshell-ai/melotts"
attachment = true
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2024-07-19"
last_updated = "2024-07-19"

[cost]
# per audio minute
input = 0.0002
output = 0

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["audio"]
