# https://developers.cloudflare.com/workers-ai/models/mistral-7b-instruct-v0.1/

name = "@cf/mistral/mistral-7b-instruct-v0.1"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-09-27"
last_updated = "2025-07-24"

[cost]
input = 0.11
output = 0.19

[limit]
context = 2824
output = 2824

[modalities]
input = ["text"]
output = ["text"]
