# https://developers.cloudflare.com/workers-ai/models/neural-chat-7b-v3-1-awq/

name = "@hf/thebloke/neural-chat-7b-v3-1-awq"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-11-15"
last_updated = "2023-11-17"

[cost]
input = 0
output = 0

[limit]
context = 4096
output = 4096

[modalities]
input = ["text"]
output = ["text"]
