# https://developers.cloudflare.com/workers-ai/models/nova-3/

name = "@cf/deepgram/nova-3"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2025-06-05"
last_updated = "2025-07-08"

[cost]
input = 0.0052
output = 0.0052

[limit]
context = 0
output = 0

[modalities]
input = ["audio"]
output = ["text"]
