# https://developers.cloudflare.com/workers-ai/models/phoenix-1.0/

name = "@cf/leonardo/phoenix-1.0"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = false
release_date = "2025-08-25"
last_updated = "2025-08-25"

[cost]
# 0.0058 per 512x512 step, 0.00011 per step
input = 0.0058
output = 0.0058

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["image"]
