# https://developers.cloudflare.com/workers-ai/models/qwen1.5-14b-chat-awq/

name = "@cf/qwen/qwen1.5-14b-chat-awq"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-02-03"
last_updated = "2024-04-30"

[cost]
input = 0
output = 0

[limit]
context = 7500
output = 7500

[modalities]
input = ["text"]
output = ["text"]
