# https://developers.cloudflare.com/workers-ai/models/resnet-50/

name = "@cf/microsoft/resnet-50"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2022-03-16"
last_updated = "2024-02-13"

[cost]
# per inference request
input = 0.0000025
output = 0

[limit]
context = 0
output = 0

[modalities]
input = ["image"]
output = ["text"]
