# https://developers.cloudflare.com/workers-ai/models/stable-diffusion-xl-base-1.0/

name = "@cf/stabilityai/stable-diffusion-xl-base-1.0"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2023-07-25"
last_updated = "2023-10-30"

[cost]
input = 0
output = 0

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["image"]
