# https://developers.cloudflare.com/workers-ai/models/uform-gen2-qwen-500m/

name = "@cf/unum/uform-gen2-qwen-500m"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2024-02-15"
last_updated = "2024-04-24"

[cost]
input = 0
output = 0

[limit]
context = 0
output = 0

[modalities]
input = ["image","text"]
output = ["text"]
