# https://developers.cloudflare.com/workers-ai/models/whisper/

name = "@cf/openai/whisper"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2023-11-07"
last_updated = "2024-08-12"

[cost]
# per audio minute
input = 0.00045
output = 0.00045

[limit]
context = 0
output = 0

[modalities]
input = ["audio"]
output = ["text"]
