name = "Gemini Live 2.5 Flash"
release_date = "2025-09-01"
last_updated = "2025-09-01"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-01"
tool_call = true
open_weights = false

[cost]
input = 0.50
output = 2.00
input_audio = 3.00
output_audio = 12.00

[limit]
context = 128_000
output = 8_000

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text", "audio"]