name = "Gemini 2.5 Flash Image (Preview)"
release_date = "2025-08-26"
last_updated = "2025-08-26"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-06"
tool_call = false
open_weights = false

[cost]
input = 0.30
output = 30
cache_read = 0.075

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text", "image"]