name = "Gemini 2.5 Flash Preview TTS"
release_date = "2025-05-01"
last_updated = "2025-05-01"
attachment = false
reasoning = false
temperature = false
knowledge = "2025-01"
tool_call = false
open_weights = false

[cost]
input = 0.50
output = 10.00

[limit]
context = 8_000
output = 16_000

[modalities]
input = ["text"]
output = ["audio"]